### ISSUE TITLE
Is get request Best Practice?

### ISSUE THREAD

**Issue by ghost** [Bike-Routes-MTP/SAP-Next-Gen-Biking#8]
Is the get request coded in best practice way?

I trigger a get request at the  "MarksRoutesViewController" in the function routesInfoContent(). 
In the StorageHelper I use prepareRequest() to prepare the http request and then call the makeRequest() in it. 

Right now, it works. i used the DispatchSemaphore to wait until the Backend sends the result back.

Question:
is there a better way to wait until i get the results? Otherwise when i delete the DispatchSemaphore, i return en empty [String: AnyObject] in the prepareRequest function. Because the return is faster than the arrival of the result from backend.

Used Branch: Bartosz-Report

Used sites:
http://stackoverflow.com/questions/42254114/how-can-we-wait-for-http-requests-to-finish

**Comment by ManuelRiess** [comment]
Yes, you could do this if you want to. The way you do it with the Semaphore is ok, I also had to do this once. Although I would question whether there is another way to do this asynchronously. There is a reason the API does not offer a synchronous way by default anymore.

As far as I can tell here, the original reason this is synchronous is to present an alert after the upload was triggered. One direction you could think about is to extend the StorageHelper and having a delegate that gets called when the data was uploaded and which can then display the result. The upload function itself also waits for the request to finish.

But since the StorageHelper as it is now, is probably used by other classes as well, the delegate approach might not be the best solution... Another way would be to post Notifications. The Button triggers the backend request, which is done asynchronously; when this is done, the StorageHelper posts a Notification with the result on which the UI listens and reacts.

The uploadToHana method is pretty big. Splitting this up might make it easier to read and maintain and help removing the synchronization with the Semaphore. You don't have to wait in the sendRequest function until the dataTask is finished. The URLSession also has a delegate method that gets called when it finished receiving data. In this delegate method you can then go on with your asynchronous handling and notify the UI that the data was uploaded (or not). Just make sure to always call UI related stuff on the main thread! Otherwise the app will either crash or behave unexpectedly.

DispatchQueue.main.async {
  stuffToDoOnTheUI()
}

If you are really curious, you could check out a "completely different" approach using NSOperations. Here you could define dependencies between the operations. One to post the data to Hana which is dependent on one to get a token... etc. It's pretty cool, but the learning curve is quite high ;)

**Comment by ManuelRiess** [comment]
Maybe to make bolder statement and cut it short: It works and is ok, but there are better ways. The UI should never ever have to wait for something from the backend. Fire the request, display a spinner, get notified in which way you like... delegates, notifications, providing a completionHandler block... there are many ways to solve this.

**Comment by ghost** [comment]
Thank you Manuel for your answer!
I know my solution is not the best solution. This is why I asked. 
I also tried the completionHandler, but maybe I couldn't get it right.
I will keep your answer, expecially the last idea in mind and try it out in the Milestone 3.

**Comment by ManuelRiess** [comment]
I was thinking about this a little bit more. You should definitely have another look at this at some later point. As I said... it can be done like this if totally necessary, but the UI should never have to wait for some other process. The main thread should not get blocked at any point. Imagine bad network conditions, or no network at all (which is not checked at all at the moment). The call to sendRequest will pause the main thread until there is a timeout from the URLSession. Also: Currently if the request returns an error, the semaphore will never get a signal.

If you block the main thread for too long, the system will kill your app.
